on: [push, pull_request]
name: CI
jobs:
  test:
    permissions:
      contents: read
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: make clean build

      - name: Test
        run: make test
